### ISSUE TITLE
No Login and Register blades / vue pages found

### ISSUE THREAD

**Issue by imranlashari** [magarrent/laravel-tailwind-boilerplate-vue-ready#1]
Did you add any Authentication scaffolding in this project?

**Comment by magarrent** [comment]
Hi @imranlashari ! No! This template, it's a starter boilerplate.

There are so many Authentications, APIs and other functionality that maybe each developer has their own method to develop or integrate.

So for this reason I've decided to keep this repo as simple as possible to avoid that.

But I'm thinking about adding additional modules to the repo like auth-module like you said, and other functionalities, but there has to be additional to the repo, not all integrated.

**Comment by magarrent** [comment]
If you only want to add basic Laravel scaffolding, just install Laravel UI:
https://laravel.com/docs/8.x/authentication

**Comment by imranlashari** [comment]
@magarrent That's great, Thank you.
